"""message

Revision ID: 074a29253203
Revises: e421733e644f
Create Date: 2024-07-07 20:38:26.998822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074a29253203'
down_revision = 'e421733e644f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
